spring:
  application:
    name: realworld-app
  datasource:
    url: jdbc:h2:file:/data/realworld-db
    username: qw
    password: qw
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  Jackson:
    deserialization:
      unwrap-root-value: true
